"""Single-cell aquifer state model: linear reservoir with base-level constraint.

Propagates a daily groundwater head h(t) under recharge forcing R(t),
linear drainage toward a base level h_base, and a time-varying specific
yield Sy(t):

    dh/dt = R / Sy − k · (h − h_base) + epsilon(t)

with `k` the recession constant (per day) and `epsilon` a small process
noise term. The base level acts as a physical lower bound on the simulated
head: it represents the hydraulic floor (local discharge level, river
stage, aquifer bottom) below which the linear-reservoir abstraction
ceases to apply.

This is the "process model" half of the state-space framework reported in
the paper, used here in *forward simulation* mode to produce the synthetic
ground-truth head series. The same equation, run in inverse mode, is the
process equation of the Kalman filter in `framework/kalman_wtf.py`.
"""
from __future__ import annotations

import numpy as np


def simulate_aquifer(
    recharge_mm_per_day: np.ndarray,
    sy_t: np.ndarray,
    k_per_day: float = 0.005,
    h_base_m: float = 0.0,
    h_initial_m: float | None = None,
    process_noise_std_m: float = 0.0,
    seed: int | None = None,
) -> np.ndarray:
    """Forward-simulate groundwater head h(t) under linear-reservoir dynamics.

    Parameters
    ----------
    recharge_mm_per_day : ndarray of shape (n_days,)
        Daily recharge forcing in millimetres per day.
    sy_t : ndarray of shape (n_days,)
        Time-varying specific yield. Either generated by
        `synthetic.dynamic_sy.generate_dynamic_sy` or a constant array.
    k_per_day : float, default 0.005
        Recession constant (per day). Larger values = faster drainage
        toward the base level.
    h_base_m : float, default 0.0
        Physical lower bound on head (m). Discharge stops when h <= h_base.
    h_initial_m : float or None
        Initial head (m). Defaults to h_base + 1.0 m for a non-trivial
        starting state.
    process_noise_std_m : float, default 0.0
        Standard deviation of zero-mean Gaussian process noise (m/day).
    seed : int or None
        Random seed for the process-noise draws.

    Returns
    -------
    h_t : ndarray of shape (n_days,)
        Daily groundwater head time series in metres above the head datum.
        This is the *ground-truth* head produced by the synthetic well;
        an observation step (sensor noise, gaps, pumping) is applied
        downstream by the synthetic-well pipeline.
    """
    n_days = len(recharge_mm_per_day)
    rng = np.random.default_rng(seed)

    if h_initial_m is None:
        h_initial_m = h_base_m + 1.0

    # Convert recharge (mm/day) to head-equivalent (m/day): divide by Sy
    # but Sy is dimensionless volume of water per volume of aquifer pores,
    # so the conversion is: dh = (R/1000 m) / Sy
    R_m = np.asarray(recharge_mm_per_day, dtype=float) / 1000.0
    sy = np.asarray(sy_t, dtype=float)
    sy = np.clip(sy, 0.01, 0.5)  # physical bounds

    h = np.empty(n_days)
    h[0] = h_initial_m

    for i in range(n_days - 1):
        recharge_rise = R_m[i] / sy[i]
        drainage = k_per_day * (h[i] - h_base_m)
        noise = (
            rng.normal(0.0, process_noise_std_m)
            if process_noise_std_m > 0
            else 0.0
        )
        h_next = h[i] + recharge_rise - drainage + noise
        # Enforce base-level constraint (physical floor)
        h[i + 1] = max(h_next, h_base_m)

    return h


__all__ = ["simulate_aquifer"]
